### PR TITLE
chore(rule): update padded-blocks rule

### PR DESCRIPTION
**Pull request by jtheoof**

### CODE REVIEW

**Review by blemoine — APPROVED** [review]
Seems ok for me

**Review by daddykotex — COMMENTED** [review]
LGTM

If I understand this correctly, it overrides the value for `switch`?

http://eslint.org/docs/rules/padded-blocks

So "never" was nerver for anything but switches, and now you force it on switch as well?

**Review by daddykotex — APPROVED** [review]

**Comment by jtheoof** [comment]
@daddykotex `never` was only equivalent to `blocks: never`, now I enforce for blocks, classes and switches. Because of @blemoine who likes to add empty lines after `classes` :)

**Comment by blemoine** [comment]
Ahhh stop, I remove my approval then.

I add an empty line at the file because it simplify the usage of lot of tools (starting with merges in git, but almost all posix tools needs to have empty lines at the end of files)

**Comment by jtheoof** [comment]
This has nothing to do with end of file.
It checks that you don't do:

```js
class MyClass {

  constructor() {}

}
```

**Comment by blemoine** [comment]
Empty line after class "header" and not after the class itself. 

Ok, my bad, I misunderstood.

**Pull request merged**
